const Config = Object.freeze({
  MAX_LIVES: 3,
  AMOUNT_QUESTIONS: 10,
  TIME_ANSWER_FAST: 10,
  TIME_ANSWER_SLOW: 20,
  POINT_FOR_CORRECT_ANSWER: 100,
  POINT_FOR_CORRECT_FAST_ANSWER: 50,
  POINT_FOR_CORRECT_SLOW_ANSWER: 50,
  POINT_FOR_ONE_LIVE: 50,
});

export default Config;
